project_id = "wgtprqsrzxdudtffbwed"

[functions.timi-chat]
verify_jwt = false

[functions.personal-ai-genius]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.generate-pathway]
verify_jwt = false

[functions.simulate-opportunities]
verify_jwt = false

[functions.match-scholarships]
verify_jwt = false
